### ISSUE TITLE
Role?

### ISSUE THREAD

**Issue by ScubaDrew** [msiegenthaler/postgres-kubernetes#1]
What is the point of the role metadata?

It errors out on me:

error validating data: found invalid field role for v1.ObjectMeta; if you choose to ignore these errors, turn validation off with --validate=false

**Comment by msiegenthaler** [comment]
Just a label, it has no special meaning, but it's actually syntactically wrong.

Thanks for pointing it out, I've updated the Readme accordingly.

**Comment by ScubaDrew** [comment]
Thanks @msiegenthaler !
